spring:
  application:
    name: book-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book_db
  kafka:
    bootstrap-servers: localhost:9092


server:
  port: 8080


